Repository thoth-station/pipeline-helpers, pull requests merged in 2021-05, with the labels that each got.

#3 Add method to gather metrics
  .aicoe-ci.yaml
  .gitignore
  .pre-commit-config.yaml
  .prow.yaml
  OWNERS
  OWNERS_ALIASES
  Pipfile
  Pipfile.lock
  README.md
  gather_metrics.py
  pyproject.toml
  thoth/pipeline_helpers/__init__.py
Labels: approved, lgtm, size/XL

#4 Adjust method
  .aicoe-ci.yaml
  OWNERS
  README.md
  gather_metrics.py
Labels: approved, size/M

#14 Add post process metrics method for pipeline helpers
  Pipfile
  Pipfile.lock
  gather_metrics.py
  post_process_metrics.py
  thoth/pipeline_helpers/common.py
Labels: approved, size/XXL

#16 update the prow resource limits
  .prow.yaml
Labels: approved, size/S

#15 Customize obejcts for AI model deployment
  customize_object_deployments.py
  gather_metrics.py
  manifests/template/deploymentconfig.yaml
  manifests/template/route.yaml
  manifests/template/service.yaml
  post_process_metrics.py
Labels: approved, size/L

#20 Add link to features test to collect metrics
  post_process_metrics.py
Labels: approved, size/XS

#23 fix variable
  customize_object_deployments.py
  gather_metrics.py
  manifests/template/deploymentconfig.yaml
  post_process_metrics.py
Labels: approved, size/S
