Repository thoth-station/pipeline-helpers, pull requests merged in 2022-03, with the labels that each got.

#45 Add script to bump base image versions to latest
  bump_base_image_version.py
Labels: approved, size/L

#48 Use init_logging from thoth_common
  Pipfile
  Pipfile.lock
  bump_base_image_version.py
Labels: approved, size/S

#51 updating pre-commit protocol and aicoe build-strategy
  .aicoe-ci.yaml
Labels: size/XS

#47 Add Quay authentication to bump image version script and skip update if version is latest
  bump_base_image_version.py
Labels: approved, size/S

#56 Add my username to maintainers
  .thoth.yaml
Labels: size/XS

#59 Fix pre-commit config
  .pre-commit-config.yaml
Labels: size/XS, approved
